.tox-template:
  tags: [bb5]

py36:
 variables:
    EXTRA_MODULES:
      archive/2019-12:py-numpy

lint:
 variables:
    EXTRA_MODULES:
      archive/2019-12:py-numpy

coverage:
 variables:
    EXTRA_MODULES:
      archive/2019-12:py-numpy


include:
- project: 'nse/ci'
  ref: main
  file:
    - '/ci/lib/tox-bb5.yml'
    - '/ci/jobs/coverage.yml'
    - '/ci/jobs/lint.yml'
    - '/ci/jobs/py36.yml'
    - '/ci/jobs/check-version.yml'

